---
title: "GIS"
author: "Shani Fourie"
date: "22/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(sf)
methods(class="sf")
marine=st_read("SAMPAZ_OR_2021_Q4.shp")
```

```{r}
#Getting the coordinates
st_crs(marine)


head(marine)

#plotting
plot(marine)
plot(marine[2])
library(tidyverse)
ggplot() +
  geom_sf(data=marine, aes(fill = `CUR_NME`))

#Cropping
ext=c(14.1,-40,25,-32)
names(ext)=c("xmin","ymin","xmax","ymax")
ext


#feeding cropped area into st_crop

marine=st_crop(marine,ext)
ggplot() + geom_sf(data=marine, aes(fill = `CUR_NME`))


```

```{r}
#calling iNaturalist locality point data from R
library(rinat)
library(tidyverse)
pc <- get_inat_obs(taxon_name = "Spheniscus demersus",
                   bounds = c(-40,14.1,-32,25),
                   maxresults = 1000)

#view the first few rows
head(pc)
class(pc)


#Make the dataframe a spatial object of class = "sf"
pc <- st_as_sf(pc, coords = c("longitude", "latitude"), crs = 4326)

#What class is it?
class(pc)

names(pc)


#plot
ggplot() + geom_sf(data=pc)


#adding in Basemaps
library(rosm)
library(ggspatial)

ggplot() + 
  annotation_map_tile(type = "osm", progress = "none") + 
  geom_sf(data=pc)

#Interactive maps with leaflet
library(leaflet)
library(htmltools)
library(tidyverse)

leaflet() %>%
  # Add default OpenStreetMap map tiles
  addTiles(group = "Default") %>%  
  # Add our points
  addCircleMarkers(data = pc,
                   group = "Spheniscus demersus",
                   radius = 3, 
                   color = "black") 

```




fibe

